### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shurakenas** [zvinger/docker-proxy-rkn#1]
502 Bad Gateway
Бот молчит

**Comment by amorev** [comment]
Можно чуть более подробную информацию?

**Comment by shurakenas** [comment]
1) запустил - docker run -it -d -p 3333:80 zvinger/docker-proxy-rkn
2) проверяю - curl --header 'Content-Type: application/json' --request 'POST' --data '{"chat_id":"xxxxxx","text":"Проверяю отправку оповещений ботом"}' "http://192.168.148.5:3333/bot_token/sendMessage"
3) получаю ошибку - 502 Bad Gateway

**Comment by shurakenas** [comment]
Также в системе Redmine есть плагин, в нем меняю https://api.telegram.org/bot на http://192.168.148.5:3333 и бот также молчит

**Comment by amorev** [comment]
Какой командой запускаете? Ваш сервер доступ из внешней сети?

**Comment by shurakenas** [comment]
docker run -d -p 3333:80 zvinger/docker-proxy-rkn - вот так и запускаю
"Ваш сервер доступ из внешней сети?" То есть?

**Comment by Alekskey** [comment]
Привет. Похоже возникновение 502 Bad Gateway связано с провайдером. 
Дома работает / На работе нет (502).

Устанавливал на Ubuntu Server 18.04.1 во время установки выбираю фичу с docker. Остальное по вашей инструкции.

Как можно отловить что провайдер гасит соединение?

**Comment by amorev** [comment]
Я верно понял, что дома работает, а в другом месте нет? Если так, то значит точно блокируется провайдером

**Comment by Alekskey** [comment]
> Я верно понял, что дома работает, а в другом месте нет? Если так, то значит точно блокируется провайдером

Верно. Есть ли какой-нибудь выход?

Поможет ли если ВМ с запущенным Docker контейнером подключить к VPN?
--- Поможет. Всё успешно получилось после того как на ВМ добавил VPN доступ. (Удобный гайд и сервис https://windscribe.com/guides/linux)
