### ISSUE TITLE
HTTP only?

### ISSUE THREAD

**Issue by JavaStarter** [zvinger/docker-proxy-rkn#2]

**Comment by JavaStarter** [comment]
Правильно я понимаю, что proxy работает только по http? Как можно его заставить работать по https?

**Comment by amorev** [comment]
Можно его также запустить на 443 порту и стандартным образом подключить к нему сертификаты. Я обычно располагаю его за  https://github.com/jwilder/nginx-proxy вместе https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion и получаю https на любом контейнере за пару действий
