### ISSUE TITLE
проксирование напрямую на API

### ISSUE THREAD

**Issue by AndreyMashukov** [zvinger/docker-proxy-rkn#4]
https://api.telegram.org - а не проще проксировать сразу на API? Не вижу смысла разделять по портам, лучше проксировать на https://api.telegram.org и подставлять аргументы из запроса и slugs

**Comment by amorev** [comment]
Спасибо! Уже реализовал в https://github.com/amorev/docker-proxy-rkn/commit/f480ba1e34c45336b7ede84fccdaf4e3123a6ef9

Сразу в голову это не пришло...
